name: merged_testnet_tools

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Clone GuillaumeFalourd/poc-github-actions PUBLIC repository
        uses: GuillaumeFalourd/clone-github-repo-action@v2
        with:
          owner: 'gathecageorge'
          repository: 'ethereum-genesis-generator'

      - name: Access cloned repository content
        run: |
          cd ethereum-genesis-generator
          git checkout master
          ls -la

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ethereum-genesis-generator
          file: ethereum-genesis-generator/Dockerfile
          push: true
          tags: gathecageorge/merged_testnet_tools:latest
